apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: bernardobraslourenco/multi-client
          ports:
            - containerPort: 3000
    